/**
 * @fileoverview Complete TypeScript type definitions for the EcoTrack platform.
 *
 * All domain models, API request/response shapes, cache types, and utility
 * interfaces are consolidated here. No `any` types — every parameter and
 * return value is explicit, enabling full IDE autocompletion and compile-time
 * safety across the entire backend.
 *
 * Organization:
 * 1. Primitives & enums
 * 2. Domain models (stored in Firestore)
 * 3. API request DTOs (validated at route layer)
 * 4. API response shapes (returned to clients)
 * 5. Cache internals
 * 6. Firestore query helpers
 * 7. Retry configuration
 *
 * @module types/eco_types
 */

// ─────────────────────────────────────────────────────────────────────────────
// 1. PRIMITIVES & ENUMS
// ─────────────────────────────────────────────────────────────────────────────

/** Google Maps travel mode strings accepted by the Directions API. */
export type TravelMode = 'DRIVING' | 'TRANSIT' | 'WALKING' | 'BICYCLING';

/** Emission source categories stored per record. */
export type EmissionCategory = 'commute' | 'utility' | 'food' | 'other';

/** Fuel types for passenger vehicle calculations. */
export type VehicleFuelType = 'PETROL' | 'DIESEL' | 'EV' | 'HYBRID';

/** Confidence level for AI extraction operations (0–1 range). */
export type ConfidenceScore = number;

// ─────────────────────────────────────────────────────────────────────────────
// 2. DOMAIN MODELS (Firestore documents)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A registered user profile.
 * Stored in Firestore at: `users/{uid}`
 */
export interface UserProfile {
  uid: string;
  email: string;
  displayName: string | null;
  photoURL: string | null;
  /** Monthly CO₂e reduction goal in kg. */
  monthlyGoalKg: number;
  createdAt: string;  // ISO 8601
  updatedAt: string;  // ISO 8601
}

/**
 * Category-specific metadata attached to an EmissionRecord.
 * All fields are optional because only certain fields apply per category.
 */
export interface EmissionMetadata {
  /** [commute] Starting address or coordinate string. */
  origin?: string;
  /** [commute] Destination address or coordinate string. */
  destination?: string;
  /** [commute] Mode of transport used. */
  travelMode?: TravelMode;
  /** [commute] One-way trip distance in kilometres. */
  distanceKm?: number;
  /** [utility] Energy consumption in kWh. */
  kWh?: number;
  /** [utility] Energy provider name extracted from bill. */
  billProvider?: string;
  /** [utility] Billing period string, e.g. "July 2025". */
  billPeriod?: string;
  /** [utility] AI extraction confidence score (0–1). */
  confidence?: ConfidenceScore;
}

/**
 * A single carbon emission record for one activity.
 * Stored in Firestore at: `users/{uid}/emissions/{recordId}`
 */
export interface EmissionRecord {
  /** Auto-generated Firestore document ID. */
  id?: string;
  /** Firebase UID of the record owner — always from the verified token. */
  userId: string;
  /** Activity category. */
  category: EmissionCategory;
  /** Carbon emissions in kg CO₂ equivalent. */
  kgCO2e: number;
  /** ISO 8601 date string (YYYY-MM-DD) for the emission event. */
  date: string;
  /** ISO 8601 creation timestamp. */
  createdAt?: string;
  /** Category-specific metadata. */
  metadata?: EmissionMetadata;
}

/**
 * A personalized eco-insight generated by the Gemini AI model.
 * Stored in Firestore at: `users/{uid}/insights/{insightId}`
 */
export interface EcoInsight {
  id: string;
  userId: string;
  /** The structured prompt sent to Gemini (for audit and debugging). */
  prompt: string;
  /** Raw markdown response text from Gemini. */
  responseText: string;
  /** Actionable tips parsed from the response. */
  tips: EcoInsightTip[];
  generatedAt: string;  // ISO 8601
  /** True if this response was served from the in-memory cache. */
  cached: boolean;
}

/**
 * A single actionable carbon-reduction tip from an EcoInsight.
 */
export interface EcoInsightTip {
  title: string;
  description: string;
  /** Which emission category this tip targets. */
  category: EmissionCategory;
  /** Estimated monthly CO₂e saving if tip is followed (kg). */
  estimatedSavingKg: number;
  difficulty: 'easy' | 'medium' | 'hard';
}

// ─────────────────────────────────────────────────────────────────────────────
// 3. API REQUEST DTOs (validated at route layer by express-validator)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Input payload for POST /api/commute.
 * All fields are validated by the route's express-validator chain.
 */
export interface CommuteInput {
  /** Starting address (max 500 characters). */
  origin: string;
  /** Ending address (max 500 characters). */
  destination: string;
  travelMode: TravelMode;
  /** Number of one-way trips to calculate (default 1). */
  trips?: number;
  /** If true, persist the record to Firestore after calculation. */
  saveRecord?: boolean;
}

/**
 * Input payload for POST /api/scan (bill scanning).
 * Image is Base64-encoded by the client before sending.
 */
export interface BillScanInput {
  /** Base64-encoded image data (no data-URI prefix). */
  imageBase64: string;
  /** MIME type of the original image. */
  mimeType: 'image/jpeg' | 'image/png' | 'image/webp' | 'application/pdf';
}

/**
 * Input payload for POST /api/insights.
 */
export interface InsightsInput {
  /** User's total monthly carbon footprint (kg CO₂e). */
  monthlyKgCO2e: number;
  /** Commute portion of the monthly total (kg CO₂e). */
  commuteKg?: number;
  /** Utility portion of the monthly total (kg CO₂e). */
  utilityKg?: number;
  /** Primary travel mode for personalised commute tips. */
  travelMode?: TravelMode | 'MIXED';
}

// ─────────────────────────────────────────────────────────────────────────────
// 4. API RESPONSE SHAPES
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Response payload for POST /api/commute.
 */
export interface CommuteResult {
  distanceKm: number;
  durationMinutes: number;
  kgCO2e: number;
  travelMode: TravelMode;
  /** Resolved display address from the Maps API. */
  originAddress: string;
  destinationAddress: string;
  /** Firestore record ID if `saveRecord` was true. */
  savedId?: string;
  /** CO₂e from driving the same trip (for comparison banner). */
  comparisonDriving?: number;
}

/**
 * Response payload for POST /api/scan.
 */
export interface BillScanResult {
  /** Energy consumption extracted from the bill (kWh), or null if not found. */
  kWhExtracted: number | null;
  /** Calculated CO₂ emissions from the extracted kWh. */
  kgCO2e: number;
  /** Energy provider name extracted by AI, or null if not found. */
  billProvider: string | null;
  /** Billing period extracted by AI (e.g., "July 2025"), or null. */
  billPeriod: string | null;
  /** AI extraction confidence (0–1). */
  confidence: ConfidenceScore;
  /** Raw summary text returned by Gemini Vision. */
  rawSummary: string;
  /** True if served from the response cache. */
  cached: boolean;
}

/**
 * Response payload for POST /api/insights.
 */
export interface InsightsResponse {
  /** Gemini-generated markdown recommendation text. */
  text: string;
  /** True if served from the response cache. */
  cached: boolean;
}

// ─────────────────────────────────────────────────────────────────────────────
// 5. CACHE INTERNALS
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A generic, TTL-aware cache entry.
 *
 * @template T - The type of the cached value.
 */
export interface CacheEntry<T> {
  /** The cached payload. */
  value: T;
  /** Unix timestamp (ms) when this entry expires. */
  expiresAt: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// 6. FIRESTORE QUERY HELPERS
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A tuple representing a single Firestore `where()` filter clause.
 * Used by BaseDB.queryCollection to build typed filter arrays.
 *
 * [fieldPath, operator, value]
 */
export type FirestoreFilter = [string, FirebaseFirestore.WhereFilterOp, string | number | boolean | null];

/**
 * Options for BaseDB.queryCollection queries.
 */
export interface QueryOptions {
  orderBy?: string;
  orderDirection?: 'asc' | 'desc';
  limit?: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// 7. RETRY CONFIGURATION
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Configuration for the withRetry exponential backoff utility.
 * All fields are optional; defaults are applied by withRetry.
 */
export interface RetryConfig {
  /** Total number of attempts (first call + retries). Default: 3. */
  maxAttempts?: number;
  /** Initial backoff delay in milliseconds. Default: 500. */
  initialDelayMs?: number;
  /** Exponential multiplier applied after each failure. Default: 2. */
  backoffFactor?: number;
  /** Maximum delay cap in milliseconds. Default: 10 000. */
  maxDelayMs?: number;
  /**
   * Predicate to determine whether an error is worth retrying.
   * Receives the unknown thrown value. Default: retries on network/5xx errors.
   */
  shouldRetry?: (error: unknown) => boolean;
}
