/**
 * @fileoverview Response Data Transfer Objects (DTOs).
 *
 * Explicitly types all HTTP response payloads returned by the EcoTrack API.
 * These interfaces act as the outbound contract — frontend types can be
 * derived from these shapes for end-to-end type safety.
 *
 * The top-level envelope shape (success/error wrapper) is defined in
 * `utils/apiResponse.ts`. These DTOs represent the `data` field.
 *
 * @module dto/responses
 */

import type { TravelMode, EmissionCategory } from '../types/eco_types.js';

/**
 * Response payload for POST /api/commute.
 *
 * Contains the Google Maps-derived distance, the calculated CO₂e
 * for the requested trip, and a comparison value for driving.
 */
export interface CommuteResponseDto {
  /** Route distance in kilometres (from Maps Directions API). */
  distanceKm: number;
  /** Estimated trip duration in minutes (from Maps Directions API). */
  durationMinutes: number;
  /** Carbon emissions for the trip in kg CO₂ equivalent. */
  kgCO2e: number;
  /** The resolved travel mode (echoed back for client display). */
  travelMode: TravelMode;
  /** Geocoded start address resolved by Google Maps. */
  originAddress: string;
  /** Geocoded end address resolved by Google Maps. */
  destinationAddress: string;
  /**
   * Firestore document ID of the persisted EmissionRecord.
   * Only present when the request included `saveRecord: true`.
   */
  savedId?: string;
  /** kgCO₂e for the equivalent DRIVING trip (comparison baseline). */
  comparisonDriving?: number;
}

/**
 * Response payload for POST /api/scan.
 *
 * Provides the kWh extracted from the utility bill image, the
 * calculated CO₂e, and AI extraction metadata.
 */
export interface ScanResponseDto {
  /**
   * Energy consumption extracted from the bill in kWh.
   * Null when the AI could not locate a numeric value.
   */
  kWhExtracted: number | null;
  /** Calculated CO₂ emissions from the extracted kWh. */
  kgCO2e: number;
  /** Energy provider name extracted by AI (or null). */
  billProvider: string | null;
  /** Billing period string extracted by AI, e.g. "July 2025" (or null). */
  billPeriod: string | null;
  /** AI extraction confidence (0–1 range). */
  confidence: number;
  /** Raw summary text from Gemini Vision (for debugging). */
  rawSummary: string;
  /** True when this response was served from the in-memory cache. */
  cached: boolean;
  /**
   * Extraction source.
   * - `"vision"`: Gemini Vision processed the image successfully.
   * - `"fallback"`: Vision failed; client should use manual entry.
   */
  source: 'vision' | 'fallback';
}

/**
 * A single actionable recommendation inside an InsightsResponseDto.
 */
export interface InsightsTipDto {
  /** Short headline for the tip (max ~60 chars). */
  title: string;
  /** Emission category this tip targets (or any other category string). */
  category: string;
  /** Emoji icon for UI display. */
  emoji?: string;
  /** Full description of the recommended action. */
  description: string;
  /** Difficulty level for the user. */
  effortLevel: 'easy' | 'medium' | 'challenging';
  /** Estimated monthly CO₂e saving in kg if followed. */
  estimatedSavingKgMonth: number;
}

/**
 * Response payload for POST /api/insights.
 *
 * Returns personalised eco-tips, either AI-generated by Gemini or
 * produced by the deterministic rules engine as a fallback.
 */
export interface InsightsResponseDto {
  /** Full AI-generated or rules-based insight text (markdown). */
  insightText: string;
  /** Structured, actionable tips parsed from the insight. */
  tips: InsightsTipDto[];
  /** True when this response was served from the in-memory cache. */
  cached: boolean;
  /** ISO 8601 timestamp of when the insight was generated. */
  generatedAt: string;
  /**
   * Generation source.
   * - `"gemini"`: Response was AI-generated by Gemini.
   * - `"rules"`: Gemini was unavailable; rules engine was used.
   */
  source: 'gemini' | 'rules';
}

/**
 * A single item in the emissions history list (GET /api/emissions).
 */
export interface EmissionRecordResponseDto {
  /** Firestore document ID. */
  id: string;
  /** Firebase UID of the record owner. */
  userId: string;
  /** Emission category. */
  category: EmissionCategory;
  /** Carbon emissions in kg CO₂ equivalent. */
  kgCO2e: number;
  /** ISO 8601 date (YYYY-MM-DD) of the emission event. */
  date: string;
  /** ISO 8601 creation timestamp. */
  createdAt?: string;
  /** Optional category-specific metadata. */
  metadata?: Record<string, unknown>;
}

/**
 * Response payload for GET /api/emissions.
 */
export interface EmissionsListResponseDto {
  /** Paginated list of emission records, newest-first. */
  emissions: EmissionRecordResponseDto[];
  /** Total count of records returned (before any limit). */
  count: number;
}

/**
 * Response payload for POST /api/emissions.
 */
export interface EmissionSaveResponseDto {
  /** Firestore document ID of the newly created record. */
  id: string;
}

/**
 * Response payload for POST /api/auth/verify.
 */
export interface AuthVerifyResponseDto {
  /** Firebase UID from the decoded token. */
  uid: string;
  /** Email address from the decoded token. */
  email: string | undefined;
  /** Display name from the decoded token. */
  name: string | undefined;
  /** Whether the email address has been verified by Firebase. */
  emailVerified: boolean;
}

/**
 * Response payload for GET /health.
 */
export interface HealthResponseDto {
  /** Always "healthy" when the server is running. */
  status: 'healthy';
  /** ISO 8601 timestamp of the response. */
  timestamp: string;
  /** npm package version from package.json. */
  version: string;
  /** Node.js environment name (production / development / test). */
  environment: string;
  /** Server uptime in seconds. */
  uptime: number;
}
