/**
 * @fileoverview AI Eco Insights page — Gemini-powered personalized recommendations.
 *
 * Allows users to input their emission data and receive personalized,
 * actionable carbon reduction tips generated by Gemini 2.0 Flash.
 *
 * Features:
 * - Emission data input form (sliders + number inputs)
 * - Streaming-style markdown renderer for AI responses
 * - Cached response indicator
 * - Copy-to-clipboard for generated insights
 * - Share as image placeholder (premium feature)
 * - Full keyboard accessibility
 */

import React, { useState, useCallback, useRef, useId } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '@context/AuthContext';
import { getCarbonCategory } from '@utils/carbonCalc.js';

// ── Lightweight markdown renderer ─────────────────────────────────────────────
// Handles: ## headings, **bold**, *italic*, bullet lists, emoji lines
function MarkdownRenderer({ text }: { text?: string | null }) {
  if (!text) {
    return null;
  }

  const lines = text.split('\n');
  const elements: React.ReactNode[] = [];
  let listBuffer: string[] = [];
  let key = 0;

  const flushList = () => {
    if (listBuffer.length > 0) {
      elements.push(
        <ul
          key={`ul-${key++}`}
          style={{
            paddingLeft: 'var(--space-6)',
            margin: 'var(--space-3) 0',
            display: 'flex',
            flexDirection: 'column',
            gap: 'var(--space-2)',
          }}
        >
          {listBuffer.map((item) => (
            <li key={`li-${key++}`} style={{ fontSize: 'var(--text-sm)', color: 'var(--text-secondary)', lineHeight: 1.6 }}>
              {renderInline(item)}
            </li>
          ))}
        </ul>
      );
      listBuffer = [];
    }
  };

  const renderInline = (content: string): React.ReactNode[] => {
    // **bold** and *italic*
    const parts = content.split(/(\*\*[^*]+\*\*|\*[^*]+\*)/g);
    return parts.map((part) => {
      if (part.startsWith('**') && part.endsWith('**')) {
        return <strong key={`bold-${key++}`} style={{ color: 'var(--text-primary)', fontWeight: 'var(--font-semibold)' }}>{part.slice(2, -2)}</strong>;
      }
      if (part.startsWith('*') && part.endsWith('*')) {
        return <em key={`italic-${key++}`} style={{ color: 'var(--color-brand-300)' }}>{part.slice(1, -1)}</em>;
      }
      return part;
    });
  };

  lines.forEach((line: string) => {
    const trimmed = line.trim();

    if (trimmed.startsWith('## ')) {
      flushList();
      elements.push(
        <h2
          key={`h2-${key++}`}
          style={{
            fontSize: 'var(--text-lg)',
            fontWeight: 'var(--font-bold)',
            color: 'var(--color-brand-300)',
            margin: 'var(--space-5) 0 var(--space-3)',
            paddingBottom: 'var(--space-2)',
            borderBottom: '1px solid var(--border-subtle)',
          }}
        >
          {trimmed.slice(3)}
        </h2>
      );
    } else if (trimmed.startsWith('### ')) {
      flushList();
      elements.push(
        <h3
          key={`h3-${key++}`}
          style={{
            fontSize: 'var(--text-base)',
            fontWeight: 'var(--font-semibold)',
            color: 'var(--text-primary)',
            margin: 'var(--space-4) 0 var(--space-2)',
          }}
        >
          {trimmed.slice(4)}
        </h3>
      );
    } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
      listBuffer.push(trimmed.slice(2));
    } else if (trimmed === '') {
      flushList();
      elements.push(<div key={`br-${key++}`} style={{ height: 'var(--space-2)' }} />);
    } else {
      flushList();
      elements.push(
        <p
          key={`p-${key++}`}
          style={{
            fontSize: 'var(--text-sm)',
            color: 'var(--text-secondary)',
            lineHeight: 1.7,
            margin: 'var(--space-2) 0',
          }}
        >
          {renderInline(trimmed)}
        </p>
      );
    }
  });

  flushList();
  return <div>{elements}</div>;
}

interface SliderInputProps {
  id: string;
  label: string;
  value: number;
  onChange: (val: number) => void;
  min?: number;
  max: number;
  step?: number;
  unit: string;
  color?: string;
}

// ── Emission data slider row ──────────────────────────────────────────────────
function SliderInput({
  id,
  label,
  value,
  onChange,
  min = 0,
  max,
  step = 0.5,
  unit,
  color,
}: SliderInputProps) {
  const pct = Math.round(((value - min) / (max - min)) * 100);
  return (
    <div style={{ marginBottom: 'var(--space-5)' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 'var(--space-2)' }}>
        <label htmlFor={id} className="form-label" style={{ marginBottom: 0 }}>
          {label}
        </label>
        <span
          style={{
            fontSize: 'var(--text-sm)',
            fontWeight: 'var(--font-semibold)',
            color: color || 'var(--color-brand-300)',
            fontFamily: 'var(--font-mono)',
          }}
        >
          {value} {unit}
        </span>
      </div>
      <input
        id={id}
        type="range"
        min={min}
        max={max}
        step={step}
        value={value}
        onChange={(e) => onChange(parseFloat(e.target.value))}
        style={{
          width: '100%',
          appearance: 'none',
          height: '6px',
          borderRadius: '3px',
          background: `linear-gradient(to right, var(--color-brand-400) ${pct}%, var(--bg-elevated) ${pct}%)`,
          outline: 'none',
          cursor: 'pointer',
        }}
        aria-valuemin={min}
        aria-valuemax={max}
        aria-valuenow={value}
        aria-valuetext={`${value} ${unit}`}
      />
      <div
        style={{ display: 'flex', justifyContent: 'space-between', marginTop: 'var(--space-1)' }}
      >
        <span style={{ fontSize: 'var(--text-xs)', color: 'var(--text-muted)' }}>{min} {unit}</span>
        <span style={{ fontSize: 'var(--text-xs)', color: 'var(--text-muted)' }}>{max} {unit}</span>
      </div>
    </div>
  );
}


// ── Main InsightsPage ────────────────────────────────────────────────────────
/**
 * AI Eco Insights page.
 * Calls Gemini via backend to generate personalized carbon reduction tips.
 *
 * @returns {React.ReactElement}
 */
interface InsightResult {
  insightText: string;
  cached: boolean;
  generatedAt: string;
}

// UI state
export default function InsightsPage() {
  const { user } = useAuth();
  const uid = useId();

  // Form state
  const [monthlyKg,   setMonthlyKg]   = useState(142.5);
  const [commuteKg,   setCommuteKg]   = useState(48.3);
  const [utilityKg,   setUtilityKg]   = useState(78.2);
  const [travelMode,  setTravelMode]  = useState('DRIVING');

  // UI state
  const [loading,     setLoading]     = useState(false);
  const [insight,     setInsight]     = useState<InsightResult | null>(null); // { text, cached, generatedAt }
  const [error,       setError]       = useState('');
  const [copied,      setCopied]      = useState(false);

  const resultRef = useRef<HTMLDivElement | null>(null);

  const category = getCarbonCategory(monthlyKg);

  const handleGenerate = useCallback(async () => {
    setLoading(true);
    setError('');
    setInsight(null);

    try {
      if (!user) {
        throw new Error('User is not authenticated.');
      }
      const API   = import.meta.env.VITE_API_BASE_URL || '';
      const token = await user.getIdToken();
      const resp  = await fetch(`${API}/api/insights`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          userId:        user.uid,
          monthlyKgCO2e: monthlyKg,
          commuteKg,
          utilityKg,
          travelMode,
        }),
      });

      const json = await resp.json();
      if (!resp.ok || !json.success) {
        throw new Error(json.message || 'Failed to generate insights. Please try again.');
      }
      setInsight(json.data);
      setTimeout(() => resultRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 100);
    } catch (err: any) {
      setError(err.message || 'Network error. Please check your connection.');
    } finally {
      setLoading(false);
    }
  }, [user, monthlyKg, commuteKg, utilityKg, travelMode]);

  const handleCopy = useCallback(async () => {
    if (!insight?.insightText) {
      return;
    }
    try {
      await navigator.clipboard.writeText(insight.insightText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // Fallback: select all text
    }
  }, [insight]);

  const modeSelectId = `${uid}-mode`;

  return (
    <section aria-labelledby="insights-heading">
      {/* ── Header ── */}
      <div style={{ marginBottom: 'var(--space-6)' }}>
        <h1
          id="insights-heading"
          className="gradient-text"
          style={{ fontSize: 'var(--text-3xl)', fontWeight: 'var(--font-extrabold)' }}
        >
          🌿 AI Eco Insights
        </h1>
        <p className="text-muted" style={{ marginTop: 'var(--space-2)' }}>
          Enter your monthly emission data below and let Gemini 2.0 Flash generate
          personalized, actionable tips to shrink your carbon footprint.
        </p>
      </div>

      {/* ── Input card ── */}
      <div className="card" style={{ marginBottom: 'var(--space-6)' }}>
        <h2
          style={{
            fontSize: 'var(--text-lg)',
            fontWeight: 'var(--font-semibold)',
            marginBottom: 'var(--space-6)',
          }}
        >
          📊 Your Monthly Emissions
        </h2>

        {/* Total monthly footprint */}
        <SliderInput
          id={`${uid}-monthly`}
          label="🌍 Total Monthly Footprint"
          value={monthlyKg}
          onChange={setMonthlyKg}
          max={600}
          unit="kg CO₂e"
          color={
            monthlyKg < 200
              ? 'var(--color-success-400)'
              : monthlyKg < 400
              ? 'var(--color-warning-400)'
              : 'var(--color-danger-400)'
          }
        />

        {/* Commute */}
        <SliderInput
          id={`${uid}-commute`}
          label="🚗 Commute Emissions"
          value={commuteKg}
          onChange={setCommuteKg}
          max={300}
          unit="kg CO₂e"
        />

        {/* Utility */}
        <SliderInput
          id={`${uid}-utility`}
          label="⚡ Utility / Energy Emissions"
          value={utilityKg}
          onChange={setUtilityKg}
          max={300}
          unit="kg CO₂e"
        />

        {/* Travel mode */}
        <div className="form-group" style={{ marginBottom: 'var(--space-6)' }}>
          <label className="form-label" htmlFor={modeSelectId}>
            🚦 Primary Travel Mode
          </label>
          <select
            id={modeSelectId}
            className="form-input"
            value={travelMode}
            onChange={(e) => setTravelMode(e.target.value)}
          >
            <option value="DRIVING">🚗 Driving (car)</option>
            <option value="TRANSIT">🚌 Public Transit</option>
            <option value="BICYCLING">🚴 Cycling</option>
            <option value="WALKING">🚶 Walking</option>
            <option value="MIXED">🔀 Mixed modes</option>
          </select>
        </div>

        {/* Footprint category badge */}
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 'var(--space-3)',
            marginBottom: 'var(--space-5)',
            padding: 'var(--space-3) var(--space-4)',
            background: 'var(--bg-tertiary)',
            borderRadius: 'var(--radius-lg)',
            border: '1px solid var(--border-subtle)',
          }}
        >
          <span style={{ fontSize: 'var(--text-xl)' }} aria-hidden="true">
            {category.emoji || '📊'}
          </span>
          <div>
            <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-muted)', marginBottom: '2px' }}>
              Your carbon category
            </p>
            <p style={{ fontWeight: 'var(--font-semibold)', color: 'var(--text-primary)' }}>
              <span className={`badge ${category.colorClass}`} style={{ marginRight: 'var(--space-2)' }}>
                {category.label}
              </span>
              {monthlyKg.toFixed(1)} kg CO₂e / month
            </p>
          </div>
        </div>

        {/* Error */}
        {error && (
          <div
            role="alert"
            aria-live="assertive"
            style={{
              background: 'hsla(0,84%,20%,0.3)',
              border: '1px solid hsla(0,84%,55%,0.4)',
              borderRadius: 'var(--radius-md)',
              padding: 'var(--space-3) var(--space-4)',
              marginBottom: 'var(--space-4)',
              color: 'var(--color-danger-400)',
              fontSize: 'var(--text-sm)',
            }}
          >
            ⚠️ {error}
          </div>
        )}

        {/* Generate button */}
        <button
          type="button"
          className="btn btn--primary"
          style={{ width: '100%', fontSize: 'var(--text-base)' }}
          onClick={handleGenerate}
          disabled={loading}
          aria-busy={loading}
          aria-label="Generate personalized eco insights using Gemini AI"
        >
          {loading ? (
            <>
              <span
                style={{
                  display: 'inline-block',
                  width: '18px',
                  height: '18px',
                  border: '2px solid currentColor',
                  borderTopColor: 'transparent',
                  borderRadius: '50%',
                  animation: 'spin 0.8s linear infinite',
                  marginRight: 'var(--space-3)',
                  verticalAlign: 'middle',
                }}
                aria-hidden="true"
              />
              Gemini is analyzing your footprint...
            </>
          ) : (
            '✨ Generate AI Insights'
          )}
        </button>
      </div>

      {/* ── Result card ── */}
      {insight && (
        <div
          ref={resultRef}
          className="card"
          role="region"
          aria-label="AI-generated eco insights"
          aria-live="polite"
          style={{
            background: 'linear-gradient(135deg, hsla(166,76%,16%,0.4), hsla(217,91%,16%,0.2))',
            border: '1px solid var(--glass-border)',
            animation: 'fadeInUp 0.4s ease-out',
          }}
        >
          {/* Result header */}
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              marginBottom: 'var(--space-5)',
              flexWrap: 'wrap',
              gap: 'var(--space-3)',
            }}
          >
            <h2
              style={{
                fontSize: 'var(--text-xl)',
                fontWeight: 'var(--font-bold)',
              }}
            >
              🤖 Your Personalized Eco Report
            </h2>
            <div style={{ display: 'flex', gap: 'var(--space-2)', alignItems: 'center' }}>
              {insight.cached && (
                <span
                  style={{
                    fontSize: 'var(--text-xs)',
                    padding: '3px 10px',
                    borderRadius: '999px',
                    background: 'hsla(217,91%,20%,0.5)',
                    color: 'var(--color-accent-400)',
                    border: '1px solid hsla(217,91%,40%,0.3)',
                  }}
                  title="This response was served from cache for speed"
                >
                  ⚡ Cached
                </span>
              )}
              <button
                type="button"
                className="btn btn--ghost btn--sm"
                onClick={handleCopy}
                aria-label={copied ? 'Copied to clipboard' : 'Copy insights to clipboard'}
              >
                {copied ? '✅ Copied!' : '📋 Copy'}
              </button>
            </div>
          </div>

          {/* Divider */}
          <div
            style={{
              height: '1px',
              background: 'var(--border-subtle)',
              marginBottom: 'var(--space-5)',
            }}
            aria-hidden="true"
          />

          {/* Rendered markdown */}
          <MarkdownRenderer text={insight.insightText} />

          {/* Footer meta */}
          <div
            style={{
              marginTop: 'var(--space-6)',
              paddingTop: 'var(--space-4)',
              borderTop: '1px solid var(--border-subtle)',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              flexWrap: 'wrap',
              gap: 'var(--space-3)',
            }}
          >
            <p style={{ fontSize: 'var(--text-xs)', color: 'var(--text-muted)' }}>
              Generated by Gemini 2.0 Flash ·{' '}
              {new Date(insight.generatedAt).toLocaleString()}
            </p>
            <button
              type="button"
              className="btn btn--secondary btn--sm"
              onClick={handleGenerate}
              aria-label="Regenerate insights with fresh AI analysis"
            >
              🔄 Regenerate
            </button>
          </div>
        </div>
      )}

      {/* ── Why this matters ── */}
      {!insight && !loading && (
        <div
          className="card"
          style={{
            background: 'var(--bg-secondary)',
            border: '1px solid var(--border-subtle)',
          }}
        >
          <h2
            style={{
              fontSize: 'var(--text-base)',
              fontWeight: 'var(--font-semibold)',
              marginBottom: 'var(--space-4)',
              color: 'var(--text-secondary)',
            }}
          >
            🧠 Powered by Gemini 2.0 Flash
          </h2>
          <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-muted)', lineHeight: 1.7, marginBottom: 'var(--space-4)' }}>
            Our AI Eco-Assistant analyzes your unique emission profile — commute habits,
            energy usage, travel patterns — and generates a personalized reduction plan.
            Not generic advice. Your data, your recommendations.
          </p>
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(3, 1fr)',
              gap: 'var(--space-3)',
            }}
          >
            {[
              { stat: '4',    label: 'Personalized tips',   icon: '💡' },
              { stat: 'CO₂', label: 'Savings estimated',    icon: '📉' },
              { stat: 'AI',  label: 'Gemini 2.0 powered',   icon: '🤖' },
            ].map(({ stat, label, icon }) => (
              <div
                key={label}
                style={{
                  textAlign: 'center',
                  padding: 'var(--space-4)',
                  background: 'var(--bg-tertiary)',
                  borderRadius: 'var(--radius-lg)',
                  border: '1px solid var(--border-subtle)',
                }}
              >
                <div style={{ fontSize: 'var(--text-2xl)', marginBottom: 'var(--space-1)' }} aria-hidden="true">{icon}</div>
                <div style={{ fontSize: 'var(--text-xl)', fontWeight: 'var(--font-bold)', color: 'var(--color-brand-300)' }}>{stat}</div>
                <div style={{ fontSize: 'var(--text-xs)', color: 'var(--text-muted)' }}>{label}</div>
              </div>
            ))}
          </div>
        </div>
      )}

      <div style={{ marginTop: 'var(--space-6)' }}>
        <Link to="/" className="btn btn--ghost">
          ← Back to Dashboard
        </Link>
      </div>
    </section>
  );
}
